# Generated by Django 3.0.5 on 2020-04-26 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kitespots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='location',
            new_name='geolocation',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='conditions',
            new_name='ranking',
        ),
        migrations.AddField(
            model_name='spot',
            name='windDirection',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
