# Generated by Django 3.0.5 on 2020-04-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitespots', '0002_auto_20200426_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='ranking',
            new_name='rating',
        ),
    ]
